@extends('layouts.basesection')
@section('dashboard')
<div>
  <h1 class="mt-3 mb-5"> Web Design</h1>
  <p>Web design encompasses many different skills and disciplines in the production 
      and maintenance of websites. The different areas of web design include web graphic design; 
      user interface design (UI design); authoring, including standardised code and proprietary software; 
      user experience design (UX design); and search engine optimization.
       Often many individuals will work in teams covering different aspects of the design process, 
       although some designers will cover them all. The term "web design" is normally used to describe the 
       design process relating to the front-end (client side) design of a website including writing markup.
        Web design partially overlaps web engineering in the broader scope of web development. 
        Web designers are expected to have an awareness of usability and if their role involves creating markup 
      then they are also expected to be up to date with web accessibility guidelines.</p>
      <br><h2>Tools and technologies</h2><br>
Web designers use a variety of different tools depending on what part of the production process they are involved in. These tools are updated over time by newer standards and software but the principles behind them remain the same. Web designers use both vector and raster graphics editors to create web-formatted imagery or design prototypes. Technologies used to create websites include W3C standards like HTML and CSS, which can be hand-coded or generated by WYSIWYG editing software. Other tools web designers might use include mark up validators and other testing tools for usability and accessibility to ensure their websites meet web accessibility guidelines.<br>
<br><br><h2>Skills and techniques</h2><br><br>
<h4>Marketing and communication design</h4><br><br>
Marketing and communication design on a website may identify what works for its target market. This can be an age group or particular strand of culture; thus the designer may understand the trends of its audience. Designers may also understand the type of website they are designing, meaning, for example, that (B2B) business-to-business website design considerations might differ greatly from a consumer targeted website such as a retail or entertainment website. Careful consideration might be made to ensure that the aesthetics or overall design of a site do not clash with the clarity and accuracy of the content or the ease of web navigation,[10] especially on a B2B website. Designers may also consider the reputation of the owner or business the site is representing to make sure they are portrayed favourably.<br>
<br><br><h4>User experience design and interactive design</h4><br><br>
User understanding of the content of a website often depends on user understanding of how the website works. This is part of the user experience design. User experience is related to layout, clear instructions and labeling on a website. How well a user understands how they can interact on a site may also depend on the interactive design of the site. If a user perceives the usefulness of the website, they are more likely to continue using it. Users who are skilled and well versed with website use may find a more distinctive, yet less intuitive or less user-friendly website interface useful nonetheless. However, users with less experience are less likely to see the advantages or usefulness of a less intuitive website interface. This drives the trend for a more universal user experience and ease of access to accommodate as many users as possible regardless of user skill. Much of the user experience design and interactive design are considered in the user interface design.
</p>

</div>
  


  <section id="services" class="services services">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
          <p></p>
      </div>

      

    </div>
  </section>




@endsection